---
# Setup/install tasks.
- name: Update Ubuntu
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_distribution == 'Ubuntu'

- name: Ensure required packages are installed.
  package:
    pkg="{{ item }}" state=present
  with_items:
    - git
    - curl
    - wget
